<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Grpc.Core" />
      <PackageReference Include="Grpc.Tools">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
      <PackageReference Include="Microsoft.NET.Test.Sdk" />
      <PackageReference Include="Moq" />
      <PackageReference Include="NUnit" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TicTacToe\TicTacToe.csproj" />
    </ItemGroup>

</Project>
