syntax = "proto3";

option csharp_namespace = "TicTacToe.Protos";

package TicTacToe.Protos;

service GameService {
  rpc MakeMove (MakeMoveRequest) returns (MakeMoveReply);
  rpc SubscribeGame(SubscribeGameRequest) returns (stream GameUpdate)
}

message GameUpdate {
  // guid
  bytes gameId = 1;
  GameStatus status = 2;
  bytes currentPlayer = 3;
  // guid
  repeated bytes players = 4;
}

message SubscribeGameRequest {
  // guid
  bytes gameId = 1;
}

enum Piece {
  Empty = 0;
  X = 1;
  O = 2;
}
enum GameStatus {
  TurnX = 0;
  TurnY = 1;
  WaitingPlayer = 2;
  GameWonX = 3;
  GameWonY = 4;
  GameDraw = 5;
}
message MakeMoveRequest {
  Piece piece = 1;
  int32 x = 2;
  int32 y = 3;
  
}
message MakeMoveReply {
  
}