syntax = "proto3";

option csharp_namespace = "TicTacToe.Protos";

package TicTacToe.Protos;

service GameService {
  rpc MakeMove (MakeMoveRequest) returns (MakeMoveReply);
  rpc SubscribeGame(SubscribeGameRequest) returns (stream GameUpdate);
}

message Player {
  // guid
  bytes playerId = 1;
  Piece selectedPiece = 2;
}

message GameUpdate {
  // guid
  bytes gameId = 1;
  GameStatus status = 2;
  bytes currentPlayer = 3;
}

message SubscribeGameRequest {
  // guid
  bytes gameId = 1;
}

enum Piece {
  Empty = 0;
  X = 1;
  O = 2;
}
enum GameStatus {
  Unspecified = 0;
  TurnX = 1;
  TurnO = 2;
  WaitingForPlayers = 3;
  WonX = 4;
  WonO = 5;
  Draw = 6;
}
message MakeMoveRequest {
  Piece piece = 1;
  int32 x = 2;
  int32 y = 3;
  
}
message MakeMoveReply {
  
}